version: '3.4'
services:
    nginx-rtmp:
        image: alfg/nginx-rtmp
        container_name: nginx-rtmp
        restart: unless-stopped
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf.template
        env_file:
            - "./.env"
        ports:
            - "1935:1935"
            - "8000:8000"
            - "8080:8080"
